

name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ORGANIZATION_HOST }}
        username: ubuntu
        key: ${{ secrets.ORGANIZATION_SSH_KEY }}
        source: "."
        target: "/home/ubuntu"

    - name: Move files to the correct directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ORGANIZATION_HOST }}
        username: ubuntu
        key: ${{ secrets.ORGANIZATION_SSH_KEY }}
        script: |
          repo_name="${{ github.repository }}"
          target_folder=${repo_name##*/}
          sudo rm -rf /var/www/html/$target_folder/*
          sudo mkdir -p /var/www/html/$target_folder
          # Move all non-hidden files
          sudo mv -f /home/ubuntu/* /var/www/html/$target_folder/
          # Move .htaccess if it exists
          if [ -f /home/ubuntu/.htaccess ]; then
              sudo mv -f /home/ubuntu/.htaccess /var/www/html/$target_folder/
          fi
          sudo rm -rf /home/ubuntu/*
          sudo chown -R ftpuser:ubuntu /var/www/html/$target_folder

    - name: Add VirtualHost to httpd.conf
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ORGANIZATION_HOST }}
        username: ubuntu
        key: ${{ secrets.ORGANIZATION_SSH_KEY }}
        script: |
          repo_name="${{ github.repository }}"
          target_folder=${repo_name##*/}
          if ! sudo grep -q "ServerName $target_folder" /etc/apache2/apache2.conf; then
            sudo bash -c 'echo "
            <VirtualHost 158.69.112.73:80>
                ServerAdmin webmaster@'"$target_folder"'
                DocumentRoot \"/var/www/html/'"$target_folder"'\"
                ServerName '"$target_folder"'
                ServerAlias www.'"$target_folder"'
                ErrorLog \"logs/'"$target_folder"'-error_log\"
                CustomLog \"logs/'"$target_folder"'-access_log\" common
                ErrorDocument 404 http://'"$target_folder"'/
            </VirtualHost>
            " >> /etc/apache2/apache2.conf'
            sudo systemctl reload apache2
          fi
