name: Generate Robots.txt and Sitemap

on:
  push:
    branches:
      - demo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Generate robots.txt and sitemap
      run: bash generate-files.sh

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add robots.txt sitemap.xml
        git commit -m "Update robots.txt and sitemap" || echo "No changes to commit"
        git push
